--- #YAML:1.0
name:               RandomJungle
version:            0.04
abstract:           Library to manipulate RandomJungle data
author:
    - Robert R. Freimuth (rrfreimuth2@yahoo.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBM::Deep:          1.0015
    Devel::StackTrace:  1.22
    Test::Simple:       0.44
    Test::Warn:         0.21
    XML::Twig:          3.34
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
