{---}
{abstract: 'Library to manipulate RandomJungle data'}
{author:}
{  - 'Robert R. Freimuth (rrfreimuth2@yahoo.com)'}
{build_requires:}
{  ExtUtils::MakeMaker: 0}
{configure_requires:}
{  ExtUtils::MakeMaker: 0}
{dynamic_config: 1}
{generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'}
{license: unknown}
{meta-spec:}
{  url: http://module-build.sourceforge.net/META-spec-v1.4.html}
{  version: 1.4}
{name: RandomJungle}
{no_index:}
{  directory:}
{    - t}
{    - inc}
{requires:}
{  DBM::Deep: 1.0015}
{  Devel::StackTrace: 1.22}
{  Test::Simple: 0.44}
{  Test::Warn: 0.21}
{  XML::Twig: 3.34}
{version: 0.05}
